server:
  host: 0.0.0.0
  port: 8080
  debug: true
  workers: 1

middlewares:
  cors:
    allow_origins:
      - "*"
    allow_methods:
      - "*"
    allow_headers:
      - "*"
    allow_credentials: false
    allow_origin_regex: null
    max_age: 600
  gzip:
    minimum_size: 500
    compresslevel: 9
  trusted_host:
    allowed_hosts:
      - "*"
    www_redirect: true
  proxy_headers:
    trusted_hosts:
      - "*"
